repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.8
  hooks:
  - id: ruff-check
    args:
    - --fix
    - --select=I
  - id: ruff-format

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.15.0
  hooks:
  - id: mypy
    args:
    - --config-file=.mypy.ini
    - --follow-imports=skip
    pass_filenames: false
    additional_dependencies:
    - types-docutils
    - lxml
    - pytest>=8.4.0
    - pytest_codspeed
    - Sphinx>=5.3.0
    - sphinxcontrib-spelling
    - types-psutil
    - psutil

- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v16.0.6
  hooks:
  - id: clang-format
    files: ^multidict/.*\.(c|h)$

- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.37.0
  hooks:
  - id: yamllint
    args:
    - --strict
    files: ^\.github/workflows/.*\.(yml|yaml)$
